### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by PWN1109** [vulkan-go/vulkan#1]
Can you make it compatible with Windows? It doesn't compile as Windows needs its own dynamic loading (windows.h instead of dlfcn.h)

**Comment by xlab** [comment]
I'll do that when I have enough time. You still can contribute your solution, it's easy to do (I'm serious). I just need to unwrap my PC with gtx after moving, setup everything back etc.

**Comment by xlab** [comment]
Btw, getting bindings autogenerated for win32-specific code might be difficult as for now, I'm getting patches ready for support MinGW.

**Comment by PWN1109** [comment]
I have an almost working patch based on dlfcn-win32 as a dependency byt i'm still bothering with some linker errors, maybe this will help you: https://github.com/dlfcn-win32/dlfcn-win32

**Comment by PWN1109** [comment]
Also, i had some other problems using the windows.h way, but i can not remember why

**Comment by xlab** [comment]
I'd stick to [LoadLibrary](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx) because it's still required to use WinAPI in order to create window, etc.

**Comment by xlab** [comment]
GLFW FTW.

**Comment by xlab** [comment]
Implemented. Now works for Windows 32-bit or 64-bit. Window initialisation and pointer hooks are done via GLFW, see:

* http://www.glfw.org/docs/latest/vulkan_guide.html
* https://github.com/go-gl/glfw

There is a demo already that does VulkanInfo:

* https://github.com/vulkan-go/demos/tree/master/vulkaninfo_desktop

To get it running you need to download [GLFW 3.2+](http://www.glfw.org/download.html) precompiled binaries, and run go install command like this (in MSYS/Git shell):

```
$ CGO_CFLAGS="-IC:\dev\glfw-3.2.1\include" CGO_LDFLAGS="-LC:\dev\glfw-3.2.1\lib-mingw-w64" go install
```

I'll resolve this issue as soon as update the README.

![](https://cl.ly/0a370G3y0p01/vulkan-golang-windows.png)

**Comment by PWN1109** [comment]
Yeah, when I try to use your command, all I get is: http://hastebin.com/figoboyotu.tex . That's the same error I've been getting when I tried to port it myself.

**Comment by PWN1109** [comment]
Nevermind. Got it fixed with "-lpsapi" linker flag

**Comment by xlab** [comment]
Whoa,thanks.  I wonder if I should include that linker flag too by default. Just for compatibility reasons.
Could you provide some specifics about your environment?

**Comment by PWN1109** [comment]
What details would you like me to provide you?

**Comment by xlab** [comment]
OS version, compiler details (`gcc -v`), `go env` maybe. Thanks.

**Comment by PWN1109** [comment]
Here you go: http://hastebin.com/lacafaboju.sql

**Comment by PWN1109** [comment]
Moreover, i'm having some issues with ACCESS_VIOLATION, but i do not know yet if it's my fault or something in bindings

**Comment by xlab** [comment]
@PWN1109 I'm running my simple examples with no problem 
<img src="https://cl.ly/1q0h0s2s0Z14/Capture1.PNG" width="600" />

Things to try:

1) Try to update and rebuild vulkan-go/vulkan;
2) Try to use `github.com/vulkan-go/glfw/v3.3/glfw` as in demos;
3) Check out https://github.com/vulkan-go/demos/tree/master/vulkandraw demo, how the main.go is organized;
4) Check if you're calling `vk.InitInstance(instance)` after creating an instance, this would re-set PFNs to instance-based ones. 

Keep in mind that I heavily updated the source and demos on the weekend, while adding support for more platforms.

**Comment by PWN1109** [comment]
I've almost copied your vulkandraw and i'm getting ACCESS_VIOLATION on vk.InitInstance, are you available on some IRC or something? Issues are quite poor solution for conversations.

**Comment by xlab** [comment]
@PWN1109 write me an email

**Comment by xlab** [comment]
Ok, so just this part has been missing:

```go
buffer, err = device.CreateBuffers()
orPanic(err)
```

I'm locking the thread, please feel free to open new issues. Thanks.
