### ISSUE TITLE
Vulkan 1.1 support

### ISSUE THREAD

**Issue by kjozic** [vulkan-go/vulkan#17]
When can we expect support for the Vulkan 1.1?

**Comment by xlab** [comment]
Yes.

**Comment by kjozic** [comment]
The first version of Vulkan SDK which included MoltenVK was 1.0.69.0. MoltenVK is a wrapper around Metal.

**Comment by gedw99** [comment]
ah. i read that a deal was doen and the closed source molten which was
built by a small company "donated" the code to the Vulkna group ?

**Comment by xlab** [comment]
@gedw99 Vulkan is an API spec over a proprietary implementation in driver. MoltenVK was once a proprietary shareware driver, now is open sourced https://github.com/KhronosGroup/MoltenVK

It is still the same layer over Metal that is supported by this project from the early beginning.

**Comment by gedw99** [comment]
Thanks for the clarification..

**Comment by dominikh** [comment]
@xlab What, other than your time, would be required to update to Vulkan 1.1? Is it merely a matter of regenerating the code and testing it, or does 1.1 involve new objects that your code generator doesn't support?

**Comment by xlab** [comment]
@dominikh Hi, mostly the header set must be reviewed, hopefully the YAML spec for the generator (vulkan.yaml) stays the same. I just updated to 1.1.88, had to do a few small changes to the generator.

It's not the update, but verification that takes time, I had to rebuild the GLFW demo for my macOS, that included MoltenVK revision, GLFW revision, also we have new loader (see #25) that I didn't have chance to test. The amount of effort to validate the changes accumulated and I spent almost a day reviewing the whole chain.

Okay, at this point 1.1.88 draws cube on Darwin, please feel free to verify on Linux / Windows. ;)
