### ISSUE TITLE
Add a package with bindings for VulkanMemoryAllocator

### ISSUE THREAD

**Issue by jclc** [vulkan-go/vulkan#31]
The Vulkan spec doesn't require the driver to handle memory allocation, leaving the user with the responsibility to deal with the memory management. For most use cases however, [the VulkanMemoryAllocator library](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) is sufficient. Would be nice having it included with the Vulkan bindings, perhaps under a subpackage called `vma`.

**Comment by jclc** [comment]
I have some preliminary work done at https://github.com/jclc/vulkan/tree/vma. This might be a little tricky since while the header defines the interface in C, the implementation is in C++.

**Comment by xlab** [comment]
@jclc what do you think about separating this into standalone repo? E.g. https://github.com/vulkan-go/vma
The project is too big to add side-projects in the root..

**Comment by xlab** [comment]
@jclc  usually by hand, using helpers that accept `uintptr`s

**Comment by jclc** [comment]
There are now (mostly) functional bindings at https://github.com/vulkan-go/vma
