### ISSUE TITLE
EnumerateInstanceLayerProperties not setting the go struct values to the C values

### ISSUE THREAD

**Issue by kohlten** [vulkan-go/vulkan#38]
So I am getting into vulkan using go and I am having some issues. When calling EnumerateInstanceLayerProperties it will return correctly, but the Go struct values are not correct. I can see internally that the internal values are correct however. 

![Screenshot from 2019-05-19 16-40-34](https://user-images.githubusercontent.com/32156797/57989816-361a1a80-7a55-11e9-992f-58881e67adb0.png)

Here is my code:
`layerNames := make([]string, 1)`
`layerNames[0] = "VK_LAYER_KHRONOS_validation"`
`layerCount := uint32(0)`
`vulkan.EnumerateInstanceLayerProperties(&layerCount, nil)`
`layers := make([]vulkan.LayerProperties, layerCount)`
`vulkan.EnumerateInstanceLayerProperties(&layerCount,` layers)`

Thanks!

**Comment by Noofbiz** [comment]
You have to do `layers.Deref()` to make the go side get the updates from the C side, I believe. I had a similar issue at some point.

**Comment by kohlten** [comment]
Thank you that fixed it.
