### ISSUE TITLE
EnumerateInstanceExtensionProperties seems to return extension properties without any name

### ISSUE THREAD

**Issue by shravanshetty1** [vulkan-go/vulkan#49]
I am trying to learn vulkan through golang following - https://vulkan-tutorial.com/.
While recreating - https://vulkan-tutorial.com/en/Drawing_a_triangle/Setup/Instance, i found my EnumerateInstanceExtensionProperties seems to return extensions without any name.

Code to reproduce issue can be found here - https://github.com/shravanshetty1/vulkan-tutorial-go/blob/master/2-instance/app/app.go#L86

**Comment by shravanshetty1** [comment]
You will have to call Dref() on every struct, not sure why this cant be done automatically by the binding

**Comment by xlab** [comment]
@shravanshetty1 that causes a full copy from C mem and allocates Go struct and memory. That can be very performance heavy.
