### ISSUE TITLE
[Question] Is there an easier way to debug errors from C?

### ISSUE THREAD

**Issue by shravanshetty1** [vulkan-go/vulkan#50]
When ever the c code errors out it just crashes the program with seg fault without anyway of telling whats wrong. Is there a way i can easily debug errors thrown from C while using this package?

I spent hours debugging swapchain, while i had just forgotten to add the swapchain extension. In bigger programs i am not sure i would have ever found the problem since there is no information to go on. Any thoughts?

**Comment by xlab** [comment]
Yo, have you tried `gdb`? :)
