### ISSUE TITLE
Conditional compilation to target Apple Metal API

### ISSUE THREAD

**Issue by joeblew99** [vulkan-go/vulkan#6]
As I understand it, to work on osx and iOS, we need to by "Molten" that is code that maps Vulkan calls to Aple's Metal API ?

I have not looked too deeply into this but historically Metal was a fork of Vulkan. Apple Just can't help itself :)

So, it maybe possible to use some conditional compilation to bypass Molten and target Metal direct ?

I am guessing you have also thought about this too but am raising it here to gather ideas / approaches .

This is super awesome project btw. Thank you so much for this work.

**Comment by xlab** [comment]
> compilation to bypass Molten and target Metal direct ?

Vulkan != Metal
This makes no sense.

https://moltengl.com/moltenvk/

**Comment by xlab** [comment]
> but historically Metal was a fork of Vulkan.

Maybe some ideas are stolen, but currently there is no relation whatsoever.

**Comment by gedw99** [comment]
http://www.tomshardware.com/news/khronos-meta-api-vulkan-metal-directx12,33962.html

have to wait to see what its like maybe
