### ISSUE TITLE
 Request to help with the translation of the page

### ISSUE THREAD

**Issue by AndrusGerman** [vulkan-go/vulkan#7]
Hello, I want to make this request to help translate the page vulkango-com. I am Spanish speaking and doing the Spanish translation of everything would make sense and would be easy to understand

**Comment by xlab** [comment]
Hi @AndrusGerman your offer is highly appreciated, I'd like to work together, so we could deliver Vulkan API knowledge to broader audience..

Currently vulkango site is plans, that means I haven't yet started to work on the content. I will notify you as soon as I will have some material to share, so you could help with translation. I plan to start in late October.

Stay tuned!

**Comment by AndrusGerman** [comment]
I will be aware of the mails to be able to help with the translation when
this project is initialized.


It will be a pleasure to work with you in the future.

2017-10-09 14:56 GMT-04:00 Maxim Kupriianov <notifications@github.com>:
